# Generated by Django 3.2.7 on 2021-09-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='update',
            new_name='updated',
        ),
    ]
